language: ruby
before_install:
  - gem install bundler --version '1.16.1'
rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
script: bundle exec rspec
